name: cicd

on:
   push:
     branches: 
       - main

jobs:

  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/chechkout@v4

      - name: build application
        run: echo "building"

      - name: run test
        run: echo "running"

      - name: deploy application
        run: echo "deploying"
